### ISSUE TITLE
FullStack - Cloudinary

### ISSUE THREAD

**Issue by Fabioseijis** [victorshp/toca_aqui#17]
images of user and instruments upload to cloudnary

**Comment by victorshp** [comment]
Hello Mr.
Vc passa a key do Cloudinary aqui, por favor?

**Comment by Fabioseijis** [comment]
Mandei no slack

Fabio Seiji dos Santos

On 29 Feb 2020, at 13:55, Victor Park <notifications@github.com> wrote:

﻿

Hello Mr.
Vc passa a key do Cloudinary aqui, por favor?

**Comment by victorshp** [comment]
Thank you.
